MyEcommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('users.urls')),
    path('', include('passwords.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout/', CheckOutView.as_view(), name='checkout-page'),
    path('product/<slug>/', ProductDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('cart/', CartView.as_view(), name='cart-page'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment-page'),
    path('request-refund/', RequestRefundView.as_view(), name='refund-page'),
    path('add-coupon/', AddCouponView.as_view(), name='coupon-page'),
]

store/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.utils import timezone

phone_regex = RegexValidator(
    regex=r'(0|\+98)?([ ]|-|[()]){0,2}9[0|1|2|3|4]([ ]|-|[()]){0,2}(?:[0-9]([ ]|-|[()]){0,2}){8}',
    message="Insert A Valid Phone Number Like: 0911*****21.")

CATEGORY_CHOICES = (
    ("S", "Shirt"),
    ("SW", "Sport wear"),
    ("OW", "Outwear"),
)

LABEL_CHOICES = (
    ("P", "primary"),
    ("S", "secondary"),
    ("D", "danger"),
)

ATTRIBUTE_CHOICES = (
    ('N', 'NEW'),
    ('BS', 'BestSeller'),
    ('PP', 'Popular')
)

STATUS_CHOICES = (
    ('PC', 'Processing'),
    ('BD', 'Being Delivered'),
    ('R', 'Received'),
)


class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    email = models.EmailField(null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    phone_number = models.CharField(validators=[phone_regex], max_length=11, blank=True)  # validators should be a list
    device_code = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        if self.user:
            return str(self.user)
        elif self.device_code:
            return str(self.device_code)


class Product(models.Model):
    title = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    image = models.ImageField(default='default.jpg', upload_to='product_images')
    description = models.TextField(default='There Is No Description')
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, blank=True)
    attribute = models.CharField(choices=ATTRIBUTE_CHOICES, max_length=2, blank=True)
    slug = models.SlugField(null=True, blank=True, unique=True)

    def __str__(self):
        if self.discount_price:
            return "{} | {}".format(self.title, self.discount_price)
        else:
            return "{} | {}".format(self.title, self.price)

    def get_absolute_url(self):
        return reverse('product-page', kwargs={
            'slug': self.slug
        })

    def get_add_to_cart(self):
        return reverse('add-to-cart', kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart(self):
        return reverse('remove-from-cart', kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    order_complete = models.BooleanField(default=False)

    def __str__(self):
        return "{} | {} | Complete: {}".format(self.customer, self.item.title, self.order_complete)

    def get_total_price(self):
        return self.item.price * self.quantity

    def get_total_discount_price(self):
        return self.item.discount_price * self.quantity

    def amount_saved(self):
        return self.get_total_price() - self.get_total_discount_price()

    def get_final_price(self):
        if self.item.discount_price != 0:
            return self.get_total_discount_price()
        else:
            return self.get_total_price()


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    phone_number = models.CharField(validators=[phone_regex], max_length=11)
    country = CountryField(multiple=False)
    state_province = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    address = models.TextField()
    zip = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return "{} | {} | {}".format(self.customer, self.country, self.address)

    def get_absolute_url(self):
        return reverse('addresses-page')


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "{} | {}".format(self.customer, self.amount)


class Coupon(models.Model):
    code = models.CharField(max_length=10)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    used = models.BooleanField(default=False)

    def __str__(self):
        return "{} | {}".format(self.code, self.amount)


class Order(models.Model):
    ref_code = models.CharField(max_length=25, blank=True, null=True)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    ordered_date = models.DateTimeField(default=timezone.now)
    order_complete = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(ShippingAddress, on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(Coupon, on_delete=models.SET_NULL, blank=True, null=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=2, blank=True, default=STATUS_CHOICES[0][0])
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return "{} | {}".format(self.customer, self.ordered_date)

    def get_total(self):
        total = 0
        for item in self.items.all():
            total += item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_absolute_url(self):
        return reverse('order-detail-page', kwargs={
            'slug': self.ref_code
        })


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    phone_number = models.CharField(validators=[phone_regex], max_length=11)
    ref_code = models.CharField(blank=True, null=True, max_length=12)
    refund_requested_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} | {} | Accepted: {}".format(self.name, self.phone_number, self.accepted)

store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from django.views.generic import DetailView, ListView, View
from django.utils import timezone
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .forms import *
from .utils import *
from django.contrib.auth.mixins import LoginRequiredMixin
from .filters import ProductFilter
from django_filters.views import FilterView


class HomeView(FilterView):
    # model = Product
    # for filtering products
    filterset_class = ProductFilter
    template_name = 'store/home.html'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        product_filter = ProductFilter(self.request.GET, queryset=Product.objects.all())
        context.update({'myFilter': product_filter})
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product.html'


def add_to_cart(request, slug):
    # function from utils.py
    customer = get_customer(request)

    product = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        customer=customer,
        item=product,
        order_complete=False,
    )
    order_qs = Order.objects.filter(customer=customer, order_complete=False)

    if order_qs.exists():
        order = order_qs[0]
        # check if order item is in order
        if order.items.filter(item__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.success(request, 'Your Quantity Was Updated.')
            return redirect('cart-page')
        else:
            order.items.add(order_item)
            messages.success(request, "This Item Was Added To Your Cart.")
            return redirect('cart-page')
    else:
        time = timezone.now()
        order = Order.objects.create(
            customer=customer,
            ordered_date=time,
        )
        order.items.add(order_item)
        messages.info(request, "This Item Was Added To Your Cart.")
        return redirect('cart-page')


def remove_from_cart(request, slug):
    # function from utils.py
    customer = get_customer(request)

    product = get_object_or_404(Product, slug=slug)
    order_item = OrderItem.objects.filter(customer=customer, order_complete=False, item=product)

    if order_item.exists():
        # delete item from OrderItem
        order_item.delete()
        messages.info(request, "This Item Was Removed From Your Cart.")
        return redirect('cart-page')
    else:
        messages.info(request, "This Item Was Not In Your Cart.")
        return redirect('product-page', slug=slug)


def remove_single_item_from_cart(request, slug):
    # function from utils.py
    customer = get_customer(request)

    product = Product.objects.get(slug=slug)
    order_item = OrderItem.objects.get(customer=customer, order_complete=False, item=product)
    if order_item.quantity > 1:
        order_item.quantity -= 1
        order_item.save()
        messages.success(request, "Your Quantity Was Updated.")
    else:
        order_item.delete()
        messages.info(request, "This Item Was Removed From Your Cart.")
    return redirect('cart-page')


class CartView(View):
    def get(self, *args, **kwargs):
        customer = get_customer(self.request)
        try:
            order, created = Order.objects.get_or_create(customer=customer, order_complete=False)
            context = {'order': order, 'couponform': CouponForm, 'DISPLAY_COUPON_FORM': True}
            return render(self.request, 'store/cart.html', context)
        except:
            messages.warning(self.request, "You Cart Is Empty.")
            return redirect('home-page')


class CheckOutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):

        # function from utils.py
        customer = get_customer(self.request)
        # for __init_ in form.py need to pass the current customer
        form = CheckOutForm(customer)

        if ShippingAddress.objects.filter(customer=customer).all().exists():
            address_exists = True
        else:
            address_exists = False

        try:
            order = Order.objects.get(customer=customer, order_complete=False)
            if order.items.count() >= 1:
                context = {
                    'order': order,
                    'form': form,
                    'couponform': CouponForm,
                    'DISPLAY_COUPON_FORM': False,
                    'address_exists': address_exists
                }

                return render(self.request, 'store/checkout.html', context)
            else:
                messages.warning(self.request, "You Cart Is Empty.")
                return redirect('cart-page')
        except ObjectDoesNotExist:
            messages.warning(self.request, "You Don't Have An Active Cart.")
            return redirect('home-page')

    def post(self, *args, **kwargs):
        if self.request.method == 'POST':
            customer = get_customer(self.request)
            form = CheckOutForm(customer, self.request.POST)
            if form.is_valid():

                # function from utils.py
                customer = get_customer(self.request)

                order = Order.objects.get(customer=customer, order_complete=False)
                address = form.cleaned_data.get('address')
                order.shipping_address = address
                order.save()

                payment_option = form.cleaned_data.get('payment_option')
                if payment_option == 'S':
                    return redirect('payment-page', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('payment-page', payment_option='paypal')
                elif payment_option == 'T':
                    return redirect('payment-page', payment_option='test-user')
            else:
                messages.warning(self.request, "Please Create An Address.")
                return redirect('checkout-page')

    # to show message if guest user goes to checkout page
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.info(self.request, "Please Create An Account To Proceed, Or Login.")
            return self.handle_no_permission()
        return super().dispatch(self.request, *args, **kwargs)


class AddCouponView(View):
    def post(self, *args, **kwargs):
        if self.request.method == 'POST':
            form = CouponForm(self.request.POST)

            if form.is_valid():
                # from utils.py
                customer = get_customer(self.request)
                code = form.cleaned_data.get('code')
                order = Order.objects.get(customer=customer, order_complete=False)
                # from utils.py
                coupon = get_coupon(self.request, code)
                order.coupon = coupon
                if order.coupon is None:
                    messages.warning(self.request, "This Coupon Code Does Not Exist.")
                    return redirect('cart-page')
                else:
                    # save and overwrite old code if exists
                    order.save()
                    messages.success(self.request, "Coupon Code Added.")
                    return redirect('cart-page')


class PaymentView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        # ORDER
        customer = get_customer(self.request)
        try:
            order = Order.objects.get(customer=customer, order_complete=False)
            if order.shipping_address:
                context = {
                    'order': order,
                    'DISPLAY_COUPON_FORM': False
                }
                return render(self.request, 'store/payment.html', context)
            else:
                messages.warning(self.request, 'Fill Out The Checkout Form')
                return redirect('checkout-page')
        except ObjectDoesNotExist:
            messages.warning(self.request, 'You Have No Active Order')
            return redirect('home-page')

    def post(self, *args, **kwargs):
        customer = get_customer(self.request)

        order = Order.objects.get(customer=customer, order_complete=False)
        token = self.request.POST.get('stripeToken')
        amount = int(order.get_total() * 100)
        # from utils.py
        p = payment_charge_post(self.request, customer, order, token, amount)
        # if error stripe occurred
        if p == 'error':
            return redirect('payment-page')
        else:
            return redirect('home-page')

    # to show message if guest user goes to checkout page
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_authenticated:
            messages.info(self.request, "Please Create An Account To Proceed, Or Login.")
            return self.handle_no_permission()
        return super().dispatch(self.request, *args, **kwargs)


class RequestRefundView(View):
    def get(self, *args, **kwargs):
        context = {
            'form': RefundForm
        }
        return render(self.request, 'store/request_refund.html', context)

    def post(self, *args, **kwargs):

        if self.request.method == 'POST':
            form = RefundForm(self.request.POST)

            if form.is_valid():
                ref_code = form.cleaned_data.get('ref_code')
                name = form.cleaned_data.get('name')
                reason = form.cleaned_data.get('reason')
                phone_number = form.cleaned_data.get('phone_number')

                try:
                    # edit order
                    order = Order.objects.get(ref_code=ref_code, order_complete=True, refund_requested=False)
                    order.refund_requested = True
                    order.save()
                    # create refund request

store/templates/store/home.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}Ecommerce Website{% endblock title %}
{% block main %}
    <!--Main layout-->
    <main class="mt-12 pt-4">
        <div class="container">

            <!--Navbar-->
            <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

                <!-- Navbar brand -->
                {#                <span class="navbar-brand">Categories:</span>#}

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
                        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">

                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <form class="nav-link" method="GET">
                                <label><i class="fas fa-vector-square"></i>Category </label>
                                {{ myFilter.form.category }}
                                <label><i class="fas fa-tags"></i>Tags </label>
                                {{ myFilter.form.attribute }}
                                <label><i class="fas fa-search"></i>Search Bar </label>
                                {{ myFilter.form.title }}
                                <button type="submit" class="btn btn-primary btn-sm">
                                    <i class="fas fa-search"></i>Search
                                </button>
                            </form>
                        </li>
                    </ul>
                    <!-- Links -->
                </div>
                <!-- Collapsible content -->

            </nav>
            <!--/.Navbar-->

            <!--Section: Products v.3-->
            <section class="text-center mb-4">

                <!--Grid row-->
                <div class="row wow fadeIn">

                    <!--Grid column-->
                    {% for product in object_list %}
                        <div class="col-lg-3 col-md-6 mb-4">
                            <!--Card-->
                            <div class="card">

                                <!--Card image-->
                                <div class="view overlay">
                                    <img src="{{ product.image.url }}"
                                         class="card-img-top"
                                         alt="">
                                    <a href="{{ product.get_absolute_url }}">
                                        <div class="mask rgba-white-slight"></div>
                                    </a>
                                </div>
                                <!--Card image-->

                                <!--Card content-->
                                <div class="card-body text-center">
                                    <!--Category & Title-->
                                    <a href="" class="grey-text">
                                        <h5>{{ product.get_category_display }}</h5>
                                    </a>
                                    <h5>
                                        <strong>
                                            <a href="{{ product.get_absolute_url }}"
                                               class="dark-grey-text">{{ product.title }}
                                                {% if product.attribute %}
                                                    <span class="badge badge-pill {{ product.get_label_display }}-color">
                                                    {{ product.get_attribute_display }}</span>
                                                {% endif %}
                                            </a>
                                        </strong>
                                    </h5>

                                    <h4 class="font-weight-bold blue-text">
                                        {% if product.discount_price %}
                                            <strong>{{ product.discount_price }}$</strong>
                                        {% else %}
                                            <strong>{{ product.price }}$</strong>
                                        {% endif %}
                                    </h4>

                                </div>
                                <!--Card content-->

                            </div>
                            <!--Card-->
                        </div>
                        <!--Fourth column-->
                    {% endfor %}

                </div>
                <!--Grid row-->

            </section>
            <!--Section: Products v.3-->

            <!--Pagination-->
            {% if is_paginated %}
                <nav class="d-flex justify-content-center wow fadeIn">
                    <ul class="pagination pg-blue">

                        <!--Arrow left-->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}"
                                   aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item active">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}
                                        <span class="sr-only">(current)</span>
                                    </a>
                                </li>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a id="num-page" class="page-link" href="?page={{ page_obj.next_page_number }}"
                                   aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            <!--Pagination-->

        </div>
    </main>
    <!--Main layout-->
{% endblock main %}

store/templates/store/order_snippet.html
<!-- TODO: put the coupon code form inside cart, and remove checkout from navbar -->

{% load cart_template_tags %}


<div
        {% if DISPLAY_COUPON_FORM %}
        class="col-md-4 mb-4"
        {% else %}
        class="col-md-12 mb-4"
        {% endif%}
>

    <!-- Heading -->
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        {% if DISPLAY_COUPON_FORM %}
            <span class="text-muted">Have A Coupon Code?</span>
        {% else %}
            <span class="text-muted">Your cart</span>
        {% endif %}
        <span class="badge badge-secondary badge-pill">{{ request|cart_item_count }}</span>
    </h4>

    <!-- Cart -->
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.items.all %}
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                    <h6 class="my-0">{{ order_item.quantity }}x {{ order_item.item.title }}</h6>
                    <small class="text-muted">{{ order_item.item.description|truncatechars:'100' }}</small>
                </div>
                <span class="text-muted">${{ order_item.get_final_price }}</span>
            </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ order.coupon.code }}</small>
            </div>
            <span class="text-success">-${{ order.coupon.amount }}</span>
        </li>
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total }}</strong>
        </li>
    </ul>
    <!-- Cart -->
    {% if DISPLAY_COUPON_FORM %}
        <!-- Promo code -->
        <form class="card p-2" method="POST" action="{% url 'coupon-page' %}">
            {% csrf_token %}
            <div class="input-group">
                {{ couponform.code }}
                <div class="input-group-append">
                    <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
                </div>
            </div>
        </form>
        <!-- Promo code -->
    {% endif %}

</div>

store/templates/store/product.html
{% extends 'store/base.html' %}

{% load static %}

{% block title %}Product{% endblock title %}

{% block main %}
    <!--Main layout-->
    <main class="mt-5 pt-4">
        <div class="container dark-grey-text mt-5">

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <img src="{{ object.image.url }}" class="img-fluid"
                         alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-md-6 mb-4">

                    <!--Content-->
                    <div class="p-4">

                        <div class="mb-3">
                            <a href="">
                                <span class="badge purple mr-1">Recommended</span>
                            </a>
                            <a href="">
                                <span class="badge {{ object.get_label_display }}-color mr-1">{{ object.get_attribute_display }}</span>
                            </a>
                        </div>

                        <p class="lead">
                            {% if object.discount_price %}
                                <span class="mr-1">
                                    <del>${{ object.price }}</del>
                                </span>
                                <span>${{ object.discount_price }}</span>
                            {% else %}
                                <span>${{ object.price }}</span>
                            {% endif %}
                        </p>

                        <p class="lead font-weight-bold">Description</p>
                        <p>{{ object.description }}</p>

                        <a href="{{ object.get_add_to_cart }}">
                            <button class="btn btn-primary btn-md my-0 p">
                                Add to cart
                                <i class="fas fa-shopping-cart ml-1"></i>
                            </button>
                        </a>


                    </div>
                    <!--Content-->

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <hr>

            <!--Grid row-->
            <div class="row d-flex justify-content-center wow fadeIn">

                <!--Grid column-->
                <div class="col-md-6 text-center">

                    <h4 class="my-4 h4">Additional information</h4>

                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta
                        odit
                        voluptates,
                        quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

            <!--Grid row-->
            <div class="row wow fadeIn">

                <!--Grid column-->
                <div class="col-lg-4 col-md-12 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg"
                         class="img-fluid"
                         alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg"
                         class="img-fluid"
                         alt="">

                </div>
                <!--Grid column-->

                <!--Grid column-->
                <div class="col-lg-4 col-md-6 mb-4">

                    <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg"
                         class="img-fluid"
                         alt="">

                </div>
                <!--Grid column-->

            </div>
            <!--Grid row-->

        </div>
    </main>
    <!--Main layout-->
{% endblock %}